# Generated by Django 6.0.2 on 2026-09-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odecola', '0002_article_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temoignage',
            name='note',
        ),
        migrations.AddField(
            model_name='acteur',
            name='image',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
